# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

# Install build dependencies for better-sqlite3
RUN apk add --no-cache python3 make g++ musl-dev linux-headers sqlite-dev

WORKDIR /app

# Install dependencies without running prepare scripts
COPY package.json package-lock.json tsconfig.json ./
RUN npm ci --ignore-scripts

# Copy source and build
COPY . .
RUN npm run build

# Ensure entry point is executable
RUN chmod +x dist/index.js

# Default CMD
CMD ["node", "dist/index.js"]
